name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: create rabbitmq container
        run: docker run -d --rm -p 5672:5672 -p 15672:15672 rabbitmq:3.8-alpine
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm run build
      - run: npm run tsc-publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
